### ISSUE TITLE
Trouble mounting VirtualBox shared folders

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/VagrantRoyaleExample#1]
When I `vagrant up` the example I get:

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000,_netdev home_vagrant_server_ /home/vagrant/server

The error output from the command was:

mount: unknown filesystem type 'vboxsf'
```

Does the guest already have Guest Additions? Do I have to also manually configure them in the host?

**Comment by JoelProminic** [comment]
I added a snippet from here to fix this:  https://github.com/DominoIDP/domino_idp/blob/93898306dd84d042e77b822320cd0755c0b38d90/Vagrantfile#L155

Note that you need to change the VirtualBox version on this line:  https://github.com/Moonshine-IDE/VagrantRoyaleExample/blob/31fba3f1b4648c90378c9ebedd743e1400ab8fb3/Vagrantfile#L35

**Comment by Aszusz** [comment]
```
No package kernel-devel-3.10.0-1127.el7.x86_64 available.
Error: Nothing to do
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` 

Stdout from the command:

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.icm.edu.pl
 * extras: ftp.icm.edu.pl
 * updates: ftp.icm.edu.pl
No package kernel-devel-3.10.0-1127.el7.x86_64 available.


Stderr from the command:

Error: Nothing to do
```

**Comment by JoelProminic** [comment]
I did some more investigation for this.  @Aszusz's last error was caused because the OS needed to be upgraded before trying to download the guest additions, or the version number was not correct.  However, after I fixed this, I still got the original "mount" error.

By my understanding, the code snippet from @JustinProminic disabled updates from vbguest and installed the guest additions manually.  However, since Vagrant tried to setup the shared folders early in the script, the shared folders did not show up until the user ran "vagrant up" again.

I tried to enable vbguest updates and disable the rest of the snippet, but I found that this gave a different mount error:

    umount: /mnt: not mounted

I found that this was also caused because the proper guest additions could not be found for the current CentOS version.  The [vbguest documentation](https://github.com/dotless-de/vagrant-vbguest/blob/main/Readme.md) recommended using the `config.vbguest.installer_options = { allow_kernel_upgrade: true }` option, which forces and OS upgrade and restart.  This is slow, but I confirmed that it works.  The final snippet looks like this:

```
    # Install guest additions with vagrant-vbguest only
    # See more details about vagrant-vbguest here:  https://github.com/dotless-de/vagrant-vbguest/blob/main/Readme.md
    if Vagrant.has_plugin?("vagrant-vbguest") then
      # We rely on a shared folder at ~/server for this example, so we need to install the guest additions.
      # Note that it is possible to use the files in /vagrant instead, but we included this as an example of shared folder support.
      config.vbguest.auto_update = true
      # suggested for CentOS - updates the OS rather than trying to find a version for the current OS.  Reboots the instance.  
      config.vbguest.installer_options = { allow_kernel_upgrade: true } 
    else
      abort "Missing vbguest plugin.  Install using 'vagrant plugin install vagrant-vbguest'"
    end
```


@Aszusz, @rat-moonshine, please use `vagrant destroy` to delete your current instance, and try a fresh test with my updates.

**Comment by Aszusz** [comment]
It's working nicely
